# Generated by Django 3.0.5 on 2022-11-07 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_resolution', '0002_auto_20221107_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dept_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_dept_id', to='ticket_resolution.Department'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='dept_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_dept_id', to='ticket_resolution.Department'),
        ),
    ]
